const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Camera3D,
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.JavaScriptInEvents.EventSheet1_Event1_Act2,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Shape3D.Exps.UID,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Shape3D.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.hexcolor,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Behaviors.Physics.Acts.ApplyForce,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Shape3D.Cnds.IsBetweenAngles,
		C3.Plugins.Shape3D.Acts.SetSize,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{"3DCamera": 0},
	{Solid: 0},
	{Physics: 0},
	{plank: 0},
	{Keyboard: 0},
	{watson: 0},
	{book: 0},
	{Mouse: 0},
	{drag: 0},
	{DrawingCanvas: 0},
	{book2: 0},
	{sherlock: 0},
	{Button: 0},
	{Text: 0},
	{Browser: 0},
	{Physics2: 0},
	{drags: 0},
	{MOUSE_LOCKX: 0},
	{MOUSE_LOCKY: 0},
	{MOUSE_LOCKUID: 0},
	{maxForce: 0}
];

self.InstanceType = {
	_3DCamera: class extends self.IInstance {},
	plank: class extends self.I3DShapeInstance {},
	Keyboard: class extends self.IInstance {},
	watson: class extends self.I3DShapeInstance {},
	book: class extends self.I3DShapeInstance {},
	Mouse: class extends self.IInstance {},
	drag: class extends self.ISpriteInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	book2: class extends self.I3DShapeInstance {},
	sherlock: class extends self.I3DShapeInstance {},
	Button: class extends self.IButtonInstance {},
	Text: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	drags: class extends self.I3DShapeInstance {}
}